name: Rust general CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest,
          - macos-10.15,
          - ubuntu-16.04,
          - ubuntu-18.04,
          - ubuntu-20.04,
          - ubuntu-latest,
          - windows-latest,
          - windows-2019,

        include:
          - os: ubuntu-latest
            profile_rustup: default
            profile_ci_flow: ci-static-code-analysis-tasks
          - os: macos-latest
            profile_rustup: default
            profile_ci_flow: ci-static-code-analysis-tasks
          - os: "macos-10.15"
            profile_rustup: minimal
            profile_ci_flow: none
          - os: "ubuntu-16.04"
            profile_rustup: minimal
            profile_ci_flow: none
          - os: "ubuntu-18.04"
            profile_rustup: minimal
            profile_ci_flow: none
          - os: "ubuntu-20.04"
            profile_rustup: minimal
            profile_ci_flow: none
          - os: "windows-latest"
            profile_rustup: minimal
            profile_ci_flow: none
          - os: "windows-2019"
            profile_rustup: minimal
            profile_ci_flow: none

    steps:
      - uses: actions/checkout@v2
      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
